services:
  -type: web
  name: Sam-project
  builCommand: pip install -r requirements.txt
  startCommand: uvicron main_copy_atlas_mongo:app --host 0.0.0.0 --port 9900
  envVars:
    -key: PYTHON_VERSION
    value: 3.12.10
